/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.phonebook.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PhonebookAddress service. Represents a row in the &quot;PHONEBOOK_PhonebookAddress&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.phonebook.model.impl.PhonebookAddressModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.phonebook.model.impl.PhonebookAddressImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PhonebookAddress
 * @see com.phonebook.model.impl.PhonebookAddressImpl
 * @see com.phonebook.model.impl.PhonebookAddressModelImpl
 * @generated
 */
@ProviderType
public interface PhonebookAddressModel extends BaseModel<PhonebookAddress>,
	GroupedModel, ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phonebook address model instance should use the {@link PhonebookAddress} interface instead.
	 */

	/**
	 * Returns the primary key of this phonebook address.
	 *
	 * @return the primary key of this phonebook address
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this phonebook address.
	 *
	 * @param primaryKey the primary key of this phonebook address
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this phonebook address.
	 *
	 * @return the uuid of this phonebook address
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this phonebook address.
	 *
	 * @param uuid the uuid of this phonebook address
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the address ID of this phonebook address.
	 *
	 * @return the address ID of this phonebook address
	 */
	public long getAddressId();

	/**
	 * Sets the address ID of this phonebook address.
	 *
	 * @param addressId the address ID of this phonebook address
	 */
	public void setAddressId(long addressId);

	/**
	 * Returns the group ID of this phonebook address.
	 *
	 * @return the group ID of this phonebook address
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this phonebook address.
	 *
	 * @param groupId the group ID of this phonebook address
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this phonebook address.
	 *
	 * @return the company ID of this phonebook address
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this phonebook address.
	 *
	 * @param companyId the company ID of this phonebook address
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this phonebook address.
	 *
	 * @return the user ID of this phonebook address
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this phonebook address.
	 *
	 * @param userId the user ID of this phonebook address
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this phonebook address.
	 *
	 * @return the user uuid of this phonebook address
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this phonebook address.
	 *
	 * @param userUuid the user uuid of this phonebook address
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this phonebook address.
	 *
	 * @return the user name of this phonebook address
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this phonebook address.
	 *
	 * @param userName the user name of this phonebook address
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this phonebook address.
	 *
	 * @return the create date of this phonebook address
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this phonebook address.
	 *
	 * @param createDate the create date of this phonebook address
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this phonebook address.
	 *
	 * @return the modified date of this phonebook address
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this phonebook address.
	 *
	 * @param modifiedDate the modified date of this phonebook address
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this phonebook address.
	 *
	 * @return the first name of this phonebook address
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this phonebook address.
	 *
	 * @param firstName the first name of this phonebook address
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this phonebook address.
	 *
	 * @return the last name of this phonebook address
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this phonebook address.
	 *
	 * @param lastName the last name of this phonebook address
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the email of this phonebook address.
	 *
	 * @return the email of this phonebook address
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this phonebook address.
	 *
	 * @param email the email of this phonebook address
	 */
	public void setEmail(String email);

	/**
	 * Returns the mobile nr of this phonebook address.
	 *
	 * @return the mobile nr of this phonebook address
	 */
	@AutoEscape
	public String getMobileNr();

	/**
	 * Sets the mobile nr of this phonebook address.
	 *
	 * @param mobileNr the mobile nr of this phonebook address
	 */
	public void setMobileNr(String mobileNr);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PhonebookAddress phonebookAddress);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PhonebookAddress> toCacheModel();

	@Override
	public PhonebookAddress toEscapedModel();

	@Override
	public PhonebookAddress toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}